---
title: "Data Tidying"
author: "Kelsey Griffin"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
```

read in catch data from https://knb.ecoinformatics.org/view/df35b.304.2

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

`select` the columns we need for analyssis
`gather` to move from wide to long
`spread` to move from long to wide
`rename` a column to indicate units

```{r}
catch_clean <- catch_df %>%
 # select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode) %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)
  #spread(key = "species", value = "catch")
  tail(catch_clean)
```

##determining why categorized as character not integer
```{r}
test <-as.numeric(catch_clean$catch_thousands)
i <- which(is.na(test) == T)
print(i)
catch_clean[i, ]
```

fix typeo in original dataset
`mutate` to create a new catch column

```{r}
catch_clean_mutated <- catch_clean %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands))%>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)%>% 
  
  select(-catch_thousands)
  
  tail(catch_clean_mutated)
```

split using `group_by`

```{r}
catch_summarized <- catch_clean_mutated %>% 
  group_by(Region) %>%
  summarize(mean_catch = mean(catch),
            n_obs = n(),
            max_catch = max(catch))

head(catch_summarized)
```

```{r}
catch_chinook <- catch_clean_mutated %>% 
  filter(species == "Chinook") %>% 
  arrange(-catch)

head(catch_chinook)

```


#joins

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)
head(region_defs)


```


```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)

```

```{r}
catch_joined <- left_join(catch_clean_mutated, region_defs, by = c("Region" = "code"))

head(catch_joined)


```

```{r}
dates_df <- data.frame(date = c("5/24/1930",
                                "5/25/1930",
                                "5/26/1930",
                                "5/27/1930",
                                "5/28/1930"),
                       stringsAsFactors = FALSE)



```

```{r}
dates_separate <- dates_df %>% 
  separate(date, into = c("month", "day", "year")) %>% 
  
unite(col = date_iso, year, month, day, sep = "-")
dates_separate

```